= Fachkonzept KIM, Feature: Erfassung und Auswertung unterstützter KIM Anwendungen
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Inhaltsverzeichnis
//:sectnums:

image::gematik_logo.svg[gematik,float="right"]

== Einführung und Ziele

Als Nutzer von KIM ist es hilfreich zu wissen, welche "KIM-Anwendung" der Empfänger mit seiner KIM E-Mail unterstützt. Wenn z. B. der Sender eines Heil- und Kostenplans vor dem Absenden erkennen kann, ob der Empfänger diesen auch technisch verarbeiten kann, dann weiß der Absender schon vor dem Versenden, ob KIM genutzt werden kann und erfährt nicht erst nach dem Versenden, dass der Empfänger noch nicht bereit ist für diese KIM-Anwendung.

Das Feature ist als Enabler für KIM gedacht. Die Information, welche KIM-Anwendungen unterstützt werden, sollen im VZD automatisch erfasst werden.

Die Information soll mit der KIM-Mailadresse verknüpft sein. Änderungen sollen nur durch Nutzer ausgelöst werden dürfen.

Akzeptanzkriterien

Die Verfügbarkeit von Payload Anwendungen wird für LE im VZD automatisch erfasst.
Es gibt eine Möglichkeit die Verfügbarkeit für Payload Anwendungen austragen zu lassen.
Es gibt eine Möglichkeit die Verfügbarkeit für Payload Anwendungen zu ändern.
Änderungen sollen vorzugsweise nur durch die Anwender ausgelöst werden dürfen, z.B. per Email oder über einen anderen einfachen und direkten Weg.

== Randbedingungen

Primärsysteme verwenden aktuell im VZD das LDAP-Directory. Um zukünftige Anwendungen, wie den TI-Messenger oder KIM 2.0 nutzen zu können, werden PS auch das FHIR-Directory unterstützen. Um die Entwicklungsaufwände für PS-Hersteller zu reduzieren, ist es sinnvoll, wenn die Datenstrukturen für die Erkennung der unterstützten KIM-Anwendungen in LDAP-Directory identisch zu den Datenstrukturen im FHIR-Directory sind. DAS FHIR-Directory soll schon jetzt alle für KIM erforderlichen Daten unterstützen, damit PS-Hersteller schon früh mit der Umstellung auf das FHIR-Directory beginnen können.

== Fachlicher Kontext

=== Anwendungsfälle

*Ein Zahnarzt möchte bei einer Krankenkasse zahnärztlicher Leistungen beantragen und genehmigen lassen*

Die passende KIM-Anwendung dafür ist EBZ (Elektronische Beantragung und Genehmigung zahnärztlicher Leistungen).
Anhand der im PS gespeicherten Patientendaten ermittelt das PS die IK-Nummer der Krankenkasse. Mit der IK-Nummer als Suchparameter wird im Verzeichnisdienst die KIM-Adresse der Krankenkasse gesucht und zusätzlich, welche KIM-Anwendungen mit dieser KIM-Adresse genutzt werden können. Im Suchergebnis ist angegeben, dass die Krankenkasse auch die KIM-Anwendung EBZ unterstützt. Das CM zeigt die Bereitschaft zum Versenden des Antrags an und der Zahnarzt füllt den Antrag aus und drückt auf senden.

*Eine Krankenkasse möchte die unterstützten KIM-Anwendungen im VZD eintragen/ändern/löschen*

Hinweis: Der Vorgang wird idealerweise automatisch ausgeführt, wenn das Backend-System zur Verarbeitung von KIM-Anwendungen (im folgenden Clientsystem genannt) ein update erhält.

Das Clientsystem kennt die unterstützten KIM-Anwendungen. Zur Veranschaulichung sollen die Anwendungen die eAU und EBZ unterstützt werden. Das Clientsystem sendet eine KIM-Nachricht ohne Inhalt an die eigene Adresse. Die KIM-Nachricht enthält jedoch im Header die Dienstkennungen der unterstützten KIM-Anwendungen.

.Beispiel, KIM-Anwendung und zugehörige Dienstkennung
|===
|KIM-Anwendung |Dienstkennung
|eAU
|eAU;Lieferung;V1.0
|EBZ
|EBZ;PAR;1.4.0
|===

Der KIM-Fachdienst (Mail Server) erkennt die KIM-Nachricht als Konfigurations-Nachricht über einen neues X-KIM Header-Element

[source, ruby]
----
X-KIM-KonfigVZD=addAppSupport
----

und trägt im VZD die Unterstützung der Anwendung gemäß Dienstkennungen ein. Über den gleichen Weg aber mit anderem Wert im X-KIM-Header-Element kann die Unterstützung für eine KIM Anwendung entfernt werden.

[source, ruby]
----
 X-KIM-KonfigVZD=removeAppSupport
----

=== Datenmodell

Die Information über unterstützte KIM-Anwendungen wird sowohl im LDAP-Directory als auch im FHIR-Directory gespeichert.

==== LDAP-Directory

Die Daten werden in der KOM-LE-Fachdaten-Datenstruktur gespeichert. Die Daten entsprechen der FHIR-Endpoint Datenstruktur.

LDAP-Attribut: endpoint

Der Wert des Attributs endpoint wird als json Datenstruktur gespeichert.

Beispiel:
[source,json]
----
{
  "status": "active",
  "connectionType": {
    "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryConnectionType",
    "code": "kim-1.5"
  },
  "name": "created by config mail",
  "payloadType": [ {
	"coding": {
		"system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryPayloadType",
		"code": "eAU;Lieferung;V1.0"
	},
	}, {
	"coding": {
		"system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryPayloadType",
		"code": "EBZ;PAR;1.4.0"
	}
  } ],
  "address": "mailto:localpart@example.kim.de"
}
----

==== FHIR-Directory

Die Endpoint Ressource ist bereits definiert: https://simplifier.net/vzd-fhir-directory/endpointdirectory[VZD-FHIR-Directory, Endpoint]

// == Lösungsvorschlag



== Weblinks

