= Dienstkennungen

Dienstkennungen unterstützen im Rahmen der Weiterverarbeitung von KIM-E-Mails das empfangende System bei der Zuordnung und Automatisierung von Vorgängen. Die nachfolgende Tabelle bietet einen Überblick über die aktuellen Dienstkennungen für die Kennzeichnung von zu versendenden Nachrichten via KOM-LE-(KIM)-Clientmodul.

Diese Dienstkennungen können bereits ab KOM-LE 1.0 optional verwendet werden. Ab KOM-LE 1.5 ist die Verwendung der Dienstkennungen jedoch obligatorisch.

Wenn Sie eine Anwendung für KIM konzipieren, welche noch nicht in dieser Liste aufgeführt ist, können Sie für diese eine Dienstkennung bei der gematik registrieren. Nutzen Sie hierfür bitte das Kontaktformular der gematik.

Bei Fragen zu Spezifikation oder Qualitätssicherung wenden Sie sich bitte an die verantwortlichen Verbände, da deren Informationen auf den Angaben dieser Verbände basieren. Die Übersicht erhebt keinen Anspruch auf Vollständigkeit.

.Dienstkennungen
[format="csv", separator="#", options="header"]
|===
Anwendung#Verantwortlich#Anwendungsbeschreibung#Dienstkennung & Kurzbeschreibung
Default#gematik GmbH#Default Dienstkennung#KIM-Mail;Default;V1.0<br>Verwendung: Diese Dienstkennung soll nicht durch den E-Mail-Client gesetzt werden und dient als Platzhalter. Diese wird ausschließlich durch das Client-Module gesetzt, wenn sie nicht anders durch den Mail-Client befüllt wurde!
Abwesenheitsnotiz#gematik GmbH#Default Abwesenheitsnotiz#KIM-Mail;Abwesend;V1.0<br>Verwendung: Diese Dienstkennung muss durch den Mail-Server beim Versand einer Abwesenheitsnotiz gesetzt werden.
|===
